### ISSUE TITLE
Accompanying documents section

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#61] opened 2020-09-15 04:35 UTC
Large and Small grant accompanying docs to upload for what is now 1.3 (will be 1.2 after correction) and what is now 2.7 (will be 2.8 after correction) is the same doc, might combine and call Fiscal sponsor agreement as currently labeled for 1.3

Planning grant accompanying docs to upload for 1.3 and 2.7is the same doc, might combine and call Fiscal sponsor agreement as currently labeled for 1.3

**Comment by derekwmiller** [comment] 2020-09-15 08:16
couple of things:

* the document upload section is not finished. 
  * The planning grant section is composed as it is in the word document that I received to work from (meaning every mention of a "file upload" is reflected in that section. 
  * The large and small grants 'inherit' from the planning grant... upon completion they will 'inherit' -- and modify as necessary.

* what is after correction? does this refer to a separate issue in github or are you referring to the new number after combining file inputs? 
 * i think my confusion with the numbering (after correction) is related to the inheritance issue mentioned above

### <b>very important</b> ... how many files are required for submission? one or two?

I think you're implying that there only need be one file. Currently, the application validation routine that checks the applications prior to giving the 'all clear to submit' is looking for two files... per the application document(s).

The way that the planning grant application reads to me is this:
* question 1.3 -- hey. if you have a fiscal sponsor, upload the contract
* question 2.7 -- tell us how you intend to manage your budget. if you have more docs that explain this... upload them.
  * question 2.7 has an 'if' clause in the text, second sentence. What if they don't have a fiscal sponsor but still want to upload a budget doc?

**Comment by WendyKoelfgen** [comment] 2020-09-15 14:25
Derek - 
The correction issue Cady is referring to is in Issue 57 regarding large grants. I made issues for each grant type but it appears that the small and planning issues have been closed.

Your logic sounds correct regarding 1.3 and 2.7 and it applies across all grant types. Fiscal sponsorship is a maybe for all.

In 2.7/8, I don't believe that we had entertained any other upload in that location given that 2.8/9 has two uploads for supporting financial documentation. 

Instead of trying to combine the uploads at this point, would it be easier to add a little language acknowledging that these two uploads could be the same document?

**Comment by WendyKoelfgen** [comment] 2020-09-15 14:46
On this, "Regarding the last bullet... I think you're implying that there only need be one file. Currently, the application validation routine that checks the applications prior to giving the 'all clear to submit' is looking for two files... per the application document." 

To be clear, the document uploads for 1.3 and 2.7 are OPTIONAL and do not apply to every applicant. Ideally, the application validation informs the applicant that these uploads are missing but does not prevent them from submitting without the uploads.

**Comment by derekwmiller** [comment] 2020-09-15 15:53
Right. The files are optional. But they are still implied.

The issue is not whether they are optional or required. I get that. The issue is whether they exist as inputs or not.

If yes -- nothing more to do.

If no -- i.e. you want to combine them into a single file input -- you need to update the language on the question. You need to provide language to the user to the effect that "this might be the same document you are uploading for question X.X". And then you need to provide additional language to the user to allow for them to submit a second file if, in fact, they have one document detailing the fiscal sponsor agreement and another document detailing their management of grant funds.

**Comment by derekwmiller** [comment] 2020-09-15 16:01
RE: @WendyKoelfgen In 2.7/8, I don't believe that we had entertained any other upload in that location given that 2.8/9 has two uploads for supporting financial documentation.

to clarify --- the text from 2.8 pasted from the document is here --

2.8  	Describe how your organization will manage and account for grant funds. If you are applying with a fiscal sponsor, provide a description of the agreements about budget management and financial controls between the applicant organization and the fiscal sponsor, including roles and responsibilities. If you already have a written agreement with your fiscal sponsor you can attach the agreement instead of writing the narrative description. \<upload file field>

**Comment by CadyLister** [comment] 2020-09-15 16:05
Large grants should have option to attach: 
1.2 fiscal sponsor agreement
2.2 optional supporting docs
2.8 fiscal sponsor agreement
2.9 financials, current year and previous three years
3.4 attachment C
3.9 resumes
6.17 Budget attachment B

**Comment by derekwmiller** [comment] 2020-09-15 16:07
cool. thanks, @CadyLister

**Comment by CadyLister** [comment] 2020-09-15 16:10
Small grants should have option to attach:
1.2 fiscal sponsor agreement
2.2 optional supporting docs
2.8 fiscal sponsor agreement
2.9 financials, current year and previous one year
3.4 attachment C
6.5 Budget attachment B

**Comment by derekwmiller** [comment] 2020-09-15 16:12
cool. thank, @CadyLister

**Comment by CadyLister** [comment] 2020-09-15 16:14
Planning grants should have option to attach:
1.3 fiscal sponsor agreement
2.8 financials, current year and previous one year
3.5 budget attachment B

**Comment by CadyLister** [comment] 2020-09-15 16:16
The review either needs to make some uploads optional or none. We might also want to add a spot where people can attach any other supporting documents as a catchall

**Comment by derekwmiller** [comment] 2020-09-16 18:12
@CadyLister -- I see your planning grants comment above from yesterday... what happened to 2.2 and 2.7?

thanks.

**Comment by CadyLister** [comment] 2020-09-16 18:22
@derekwmiller - You are correct, that list is missing 2.2 and 2.7. In my defense I got really sick yesterday afternoon so was not bringing my A game. I will double check Small and Large lists now.

**Comment by derekwmiller** [comment] 2020-09-16 18:23
Sorry to hear that! And no worries on the lists. Thanks for the response and attention.

**Comment by CadyLister** [comment] 2020-09-16 18:35
ok, Large grant list is correct, Small grant should have option to upload resumes is 3.8 added but is otherwise accurate

**Comment by derekwmiller** [comment] 2020-09-16 18:47
ok. thank you.

**Comment by WendyKoelfgen** [comment] 2020-09-16 20:05
Planning grants shoul

**Comment by WendyKoelfgen** [comment] 2020-09-16 20:06
Sorry. Accidentally "closed" the issue when i was just trying to exit the comment field.

**Comment by derekwmiller** [comment] 2020-09-16 20:23
no worries

**Comment by derekwmiller** [comment] 2020-09-17 18:54
@CadyLister @WendyKoelfgen I'm going to close this. You'll notice that I reworked the file upload process. Didn't really like how it was laid out or functioning.

New approach is cleaner. Also allows for users to attach other supporting documentation as they see fit. That desire was mentioned in this thread.

**Closed as completed by derekwmiller** 2020-09-17 18:54 UTC
Labels: priority, small grant, large grant, planning grant
