### ISSUE TITLE
Converting scores from scale to actual value

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#102] opened 2020-11-19 00:54 UTC
When we finalize scores we need to convert each criterion score from the 0-4 scale to the actual value of the criterion. The formula is "point value of the criterion" divided by 4 multiplied by "score given by review panel". The criterion have different values depending on the type of grant and within small and large grants also depending on the type of project (its in those summary tables). If this isn't clean let's chat.

**Comment by derekwmiller** [comment] 2020-12-16 02:31
this sounds clear enough but likely easier implemented with a quick chat. i'll put something on that calendar

**Comment by derekwmiller** [comment] 2021-01-11 02:29
duplicate of #120

**Closed as completed by derekwmiller** 2021-01-11 02:29 UTC
